### ISSUE TITLE
Installation issue: Whoosh backend >= 2.5 required?

### ISSUE THREAD

**Issue by varrunr** [WiseEarthTechnology/CrisisCommunicator#20]
While installing Crisis Communication as per the INSTALL document, create database fails at last step stating that Whoosh backend >= 2.5 required in spite of requirements stating that only 2.4 is required.

$ python manage.py syncdb

Stacktrace:

```
(CrisisComm)varrunr@ubuntu:~/CrisisCommunicator/webapp$ python manage.py syncdb
Creating tables ...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 110, in handle_noargs
    emit_post_sync_signal(created_models, verbosity, interactive, db)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/core/management/sql.py", line 189, in emit_post_sync_signal
    interactive=interactive, db=db)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/contrib/auth/management/__init__.py", line 35, in create_permissions
    ctype = ContentType.objects.get_for_model(klass)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 42, in get_for_model
    defaults = {'name': smart_unicode(opts.verbose_name_raw)},
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/db/models/manager.py", line 134, in get_or_create
    return self.get_query_set().get_or_create(**kwargs)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/db/models/query.py", line 452, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/haystack/signals.py", line 47, in handle_save
    index = self.connections[using].get_unified_index().get_index(sender)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 98, in __getitem__
    self._connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 51, in load_backend
    return import_class(full_backend_path)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 18, in import_class
    module_itself = importlib.import_module(module_path)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/varrunr/.virtualenvs/CrisisComm/local/lib/python2.7/site-packages/haystack/backends/whoosh_backend.py", line 50, in <module>
    raise MissingDependency("The 'whoosh' backend requires version 2.5.0 or greater.")
haystack.exceptions.MissingDependency: The 'whoosh' backend requires version 2.5.0 or greater.
```

**Comment by bithinalangot** [comment]
Can you try upgrading it.

Thank you
Bithin Alangot http://bithin.wordpress.com
Research Assistant
Amrita Center for Cyber Security
amrita.edu

_Human effort is in our hands, but grace is in god's hands_

**Comment by varrunr** [comment]
Yes, upgrading works. But I want to confirm if this is an issue just with me or a global issue, which means it would be good if someone else can reproduce this issue. Or was the intended version 2.5 instead of 2.4?

**Comment by bithinalangot** [comment]
It happened to Linkesh too, I think it need to be updated in the INSTALL
document.

Thank you
Bithin Alangot http://bithin.wordpress.com
Research Assistant
Amrita Center for Cyber Security
amrita.edu

_Human effort is in our hands, but grace is in god's hands_

**Comment by varrunr** [comment]
OK, I will make the change.
PS: Leave your signature out of comments(if you're doing a reply to email thing).

**Comment by swiftarrow** [comment]
Awesome guys!  Varrun, thanks for the detail!  I mentioned you guys in my 120 second pitch yesterday!
